dir: "internal/mocks"
disable-version-string: True
outpkg: "mocks"
with-expecter: True
issue-845-fix: True
resolve-type-alias: False
packages:
  "github.com/dsh2dsh/expx-dotenv":
    interfaces:
      Filer:
